Repository privacy-tech-lab/privacy-pioneer-web-crawler, pull requests merged in 2024-04, with the labels that each got.

#32 Update Readme #31
  README.md
Labels: documentation

#34 Issue 33 (Fixes to crawler error handling)
  rest-api/index.js
  selenium-crawler/local-crawler.js
Labels: bug

#40 Update general-top-525.csv (issue #36)
  crawl-lists/general-top-525.csv
Labels: crawl-list
